Switch to Ubuntu Desktop 20.04 LTS (#78)
Resolves #75 (Switch to Ubuntu Desktop 20.04 LTS).

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -78,12 +78,19 @@ function log_event()
     fi
 }
 
-function configure_apt_package_sources()
+function enable_boot_messages()
 {
-    if ! sudo sed -i '/^deb/ s/$/ contrib non-free/' "/etc/apt/sources.list"; then
-        abort "apt package sources configuration failure"
+    if ! sudo sed -i 's/quiet splash//g' "/etc/default/grub"; then
+        abort "boot messages enable failure"
     fi
 
+    if ! sudo update-grub; then
+        abort "GRUB update failure"
+    fi
+}
+
+function configure_apt_package_sources()
+{
     if ! sudo apt-key add "$repository/apt/keys/google/linux_signing_key.pub"; then
         abort "Google apt package signing key installation failure"
     fi
@@ -151,6 +158,8 @@ function configure_environment()
     ensure_environment_has_not_been_configured
 
     log_event "configuration started"
+
+    enable_boot_messages
 
     configure_apt_package_sources
 
