Switch to KiCad 6.0 (#132)
Resolves #131 (Switch to KiCad 6.0).

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -99,6 +99,10 @@ function configure_apt_package_sources()
     if ! echo "deb http://dl.google.com/linux/chrome/deb stable main" | sudo tee "/etc/apt/sources.list.d/google-chrome.list"; then
         abort "Google Chrome apt package repository configuration failure"
     fi
+
+    if ! sudo add-apt-repository -y ppa:kicad/kicad-6.0-releases; then
+        abort "KiCad 6.0 releases PPA addition failure"
+    fi
 }
 
 function purge_modemmanager()
